version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:11
        steps:
            - checkout
            - run:
                  name: 'Install Dependencies'
                  command: yarn install
            - run:
                  name: 'Build'
                  command: yarn build
            - run:
                  name: 'Package Extension'
                  command: |
                      cd dist
                      zip -r ../dist.zip .
            - persist_to_workspace:
                  root: /home/circleci/project
                  paths:
                      - dist.zip

    publish:
        docker:
            - image: circleci/node:11
        steps:
            - attach_workspace:
                  at: /workspace
            - run:
                  name: 'Publish Extension'
                  command: |
                      ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
                      curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T /workspace/dist.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
                      curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"

workflows:
    version: 2
    main:
        jobs:
            - build
            - publish:
                  requires:
                      - build
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /.*/
