version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:11
        steps:
            - checkout
            - run:
                  name: 'Install Dependencies'
                  command: yarn install
            - run:
                  name: 'Build'
                  command: yarn build
            - run:
                  name: 'Package Extension'
                  command: |
                      cd dist
                      zip -r ../dist.zip .
            - persist_to_workspace:
                  root: /home/circleci/project
                  paths:
                      - dist.zip

    publish:
        docker:
            - image: cibuilds/chrome-extension:latest
        steps:
            - attach_workspace:
                  at: /workspace
            - run:
                  name: 'Publish Extension'
                  command: publish /workspace/dist.zip

workflows:
    version: 2
    main:
        jobs:
            - build
            - publish:
                  requires:
                      - build
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /.*/
